version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRE_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRE_DB: nest
    networks:
      - freecodecamp
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRE_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRE_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp: 